feature: cancancan
Hardboy1208/RoR_course pull request #12
Opened 2018-05-11 08:00 UTC by Hardboy1208

2018-05-11 08:31 UTC, vkurennov requested changes

2018-05-11 08:31 UTC, vkurennov commented on app/models/ability.rb
> +    can :update, [Question, Answer, Comment], user: user
Лучше сравнивать по user_id, чтобы не тянуть из базы ассоциацию

2018-05-11 08:31 UTC, vkurennov commented on app/controllers/concerns/retracted.rb
>        if !current_user.author_of?(@retractable) && !current_user.already_voted?(@retractable)
Вот эти условия и нужно перенести в правила авторизации, в контроллерах их быть не должно

2018-05-11 08:31 UTC, vkurennov commented on app/views/questions/index.html.haml
> +- if can?(:create, Question)
Во всех видах условия должны быть заменены на вызов `can?`. Т.е. проверки в контроллерах и видах полностью заменяются на CanCanCan

2018-05-11 13:46 UTC, vkurennov requested changes

2018-05-11 13:46 UTC, vkurennov commented on app/views/answers/_answer.html.haml
> +        - if can?(:destroy, Answer) && current_user.author_of?(answer)
Не должно быть проверок на author_of? в видах/контроллерах. Они полностью заменяются на can?, т.е. 
`can?(:destroy, Answer)` как раз и определяет автор это или нет.

2018-05-11 13:46 UTC, vkurennov commented on app/models/ability.rb
> +    can :rating_up, [Question, Answer]
Ты не понял. У тебя в контроллере были более сложные проверки - автор это или нет, голосовал он или нет и т.д. Вот это все должно проверяться в правилах теперь. А вызов авторизации в контроллерах для этих методов и должен определить по правилам, может юзер выполнить это действие или нет

2018-05-11 13:46 UTC, vkurennov commented on app/views/answers/_answer.html.haml
> +        - if can?(:destroy, Answer) && current_user.author_of?(answer)
И так для всех проверок в контроллере и видах.

2018-05-11 14:01 UTC, Hardboy1208 commented on app/models/ability.rb
> +    can :rating_up, [Question, Answer]
Вот сейчас реально не понял, как это писать

2018-05-15 12:36 UTC, vkurennov approved these changes

2018-05-15 12:36 UTC, vkurennov commented on app/models/ability.rb
> +    can :rating_down, [Question, Answer] do |obj|
Если у 2-х экшенов условия одинаковые, то не стоит дублировать, можно написать так:

```
can [:rating_up, :rating_down], [Question, Answer] do |obj|
  !user.author_of?(obj)
end
```

2018-05-15 12:36 UTC, vkurennov commented on app/models/ability.rb
> +    can :rating_reset, [Question, Answer] do |obj|
Здесь надо проверять, что голос создан этим юзером. Для этого, надо в контроллере вручную вызвать `authorize!` для этого метода и передать объект голоса, а не вопрос/ответ.

2018-05-16 13:28 UTC, merged