feature:
Hardboy1208/RoR_course pull request #8
Opened 2018-04-13 08:07 UTC by Hardboy1208

2018-04-13 12:32 UTC, vkurennov requested changes

2018-04-13 12:32 UTC, vkurennov commented on app/controllers/concerns/retracted.rb
> +    if !current_user.author_of?(@retractable) && current_user.already_voted?(@retractable)
Тут другое условие: пользователь может удалить только тот голос, который он и создал за данный объект

2018-04-13 12:32 UTC, vkurennov commented on app/models/concerns/retractable.rb
> +  def diff_like
Плохое решение. Нет смысла хранить значение голоса как булево поле. Так тебе приходится делать 2 запроса на кол-во и потом еще и вычитать одно из другого. А если сразу записывать в значение +1/-1, то одним методом sum можно из базы сразу получить сумму

2018-04-13 12:32 UTC, vkurennov commented on app/controllers/concerns/retracted.rb
> +        redirect_to question_path(@retractable)
У нас по заданию, все это нужно сделать через json. JSON - это ajax-запрос, т.е. в фоне, в фоне нет смысла делать редирект, т.к. редирект тоже пройдет в фоне и пользователь ничего не увидит.

2018-04-13 12:32 UTC, vkurennov commented on app/controllers/concerns/retracted.rb
> +    if !current_user.author_of?(@retractable) && !current_user.already_voted?(@retractable)
А что будет рендериться, если это или вложенное условие не выполнится?

2018-04-13 12:32 UTC, vkurennov commented on app/models/user.rb
> +    object.ratings.where(user_id: self).empty? ? false : true
Лучше так: `object.ratings.exists?(user: self)`

2018-04-13 12:32 UTC, vkurennov commented on config/routes.rb
> +    resources :answers, concerns: :retractable do
Так, пора объявить этот ресурс как shallow, а то дальше будет совсем плохо

2018-04-13 12:32 UTC, vkurennov commented on spec/acceptance/answers_and_questions/rating_for_answer_spec.rb
> +    question
Если объект нужен перед тестом, объяви его через `given!`

2018-04-13 12:32 UTC, vkurennov commented on spec/acceptance/answers_and_questions/rating_for_answer_spec.rb
> +  scenario 'unauthorized user can not vote for his answer' do
Если тетс для не авторизированного юзера, то откуда в тесте тогда sign_in?

2018-04-13 12:32 UTC, vkurennov commented on spec/acceptance/answers_and_questions/rating_for_answer_spec.rb
> +  scenario 'The author can vote for his answer' do
Так ведь автор не может голосовать за свой ответ.

2018-04-16 14:26 UTC, Hardboy1208 commented
С роутингом когда сделал shallow: true пришлось много где править и сломалось тоже почти все, так и не понял как поправить. Давайте пока оставим так, не вижу большой проблемы в таком роутинге

2018-04-17 07:20 UTC, vkurennov requested changes
Где тесты контроллеров и моделей? У тебя есть код в консернах, его и нужно тестировать. Пока можно продублировать тесты для вопроса и ответа, позже научимся выносить общие тесты.

2018-04-17 07:20 UTC, vkurennov commented on app/assets/javascripts/answers.coffee
> +    $('.vote-' + question_id).html('<p>' + vote.positive_count + ' (' + vote.positive_persent + '%) ' + ' / ' + vote.negative_count + ' (' + vote.negative_persent + '%) ' + ' | ' + vote.result + '</p
Не подскажешь, откуда в json возьмутся поля positive_count, positive_persent и т.п., если ты их не возвращаешь? Или это какой-то старый код, который не используется? Тогда зачем он здесь?

2018-04-17 07:20 UTC, vkurennov commented on app/assets/javascripts/questions.coffee
> +$ ->
Нужно еще и на turbolinks:load вешать

2018-04-17 07:20 UTC, vkurennov commented on app/models/concerns/retractable.rb
> +  def all_likes
Я не увидел где используется этот метод и следующий. А раз они нигде не используются, то зачем тогда вообще они нужны?

2018-04-17 07:20 UTC, vkurennov commented on app/views/answers/_answer.html.haml
> +      = link_to '+1', rating_up_question_answer_path(@question, answer), method: :patch
Роутинг стоит переделать как раз потому, что ты включаешь объект @question там, где он не нужен. У тебя есть ответ, этого достаточно.

2018-04-17 14:17 UTC, vkurennov requested changes

2018-04-17 14:17 UTC, vkurennov commented on app/assets/javascripts/questions.coffee
> +  $('a.rating-link').bind 'ajax:success', (e) ->
У тебя же селекторы одинаковые, что для вопросов, что для ответов. Т.е. для любой ссылки будут оба этих метода вызываться, кроме того, они еще и называются одинаково, т.е. один переопределяет другой. Вот только почему-то ты уверен, что в одном случае будет именно ответ, а в другом вопрос.

В целом, даже хорошо, что они так похоже - это указывает на то, что можно обойтись одним обработчиком. А тип получить из json (если передавать не только id объекта, но и его тип).

2018-04-17 14:17 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      author.questions.first.answers.first.ratings.create(user_id: not_author.id, like: 1)
1. Тут лучше несколько голосов создать, положительных и отрицательных, а потом проверить результат
2. Зачем такое длинное обращение к ответу? Почему бы просто не создать через фабрики ответ не важно с каким юзером и вопросом и для него не создать нужные голоса?

2018-04-17 14:17 UTC, vkurennov commented on spec/models/question_spec.rb
> +  describe '#diff_like' do
См. комментарий к answer_spec

2018-04-18 08:52 UTC, vkurennov approved these changes

2018-04-18 09:59 UTC, merged